name: Publish Container

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Base Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./base
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dev-node:v1
      
      - name: Build Firebase Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./firebase
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dev-firebase:v1
